#!/usr/bin/env python3
"""
Train a Stage-1 pH/Hamiltonian coefficient model for Ackermann navigation.

This restores the intended learning object:

    scan/local context -> Hamiltonian/ICP coefficients -> pH surrogate flow
                         -> Ackermann command adapter

The neural network does not directly learn an action sequence. It predicts
context-dependent coefficients for a shaped potential

    V(q) = beta_g V_goal(q) + sum_j alpha_j B_ICP(d_j(q))
           + stage_gain V_stage(q) + memory_amp V_mem(q),

plus damping and tangential-port gains. The training loss compares a short pH
surrogate rollout to the teacher rollout generated by the Stage-1 simulator.
"""
from __future__ import annotations

import argparse
import json
import math
import os
from dataclasses import dataclass, asdict
from typing import Any, Dict, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader

from scripts.stage1_ackermann_scan import (
    AckermannCfg,
    AdapterCfg,
    LaserScanCfg,
    SceneCfg,
    RecoveryCfg,
    Stage1AckermannDataset,
    Stage1Cfg,
    collate_stage1,
    project_twist_torch,
    stage1_cfg_to_dict,
)


# -----------------------------------------------------------------------------
# Model
# -----------------------------------------------------------------------------

class PositiveHead(nn.Module):
    def __init__(self, d_in: int, lo: float = 1e-4, scale: float = 1.0):
        super().__init__()
        self.net = nn.Sequential(nn.Linear(d_in, 96), nn.ReLU(), nn.Linear(96, 1))
        self.lo = float(lo)
        self.scale = float(scale)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.lo + self.scale * F.softplus(self.net(x)).squeeze(-1)


class StagePHCoefNet(nn.Module):
    """Context-conditioned Hamiltonian/ICP coefficient network.

    Inputs:
      obs_feats:  [B,N,6] pseudo-obstacle tokens in robot/body frame
      obs_mask:   [B,N]
      goal_feats: [B,8] local goal/history features

    Outputs:
      alphas:       [B,N] obstacle ICP weights
      beta_goal:    [B]   goal-potential strength
      beta_icp:     [B]   global soft ICP temperature/gain
      gamma:        [B]   viscous damping in virtual pH flow
      tangent_gain: [B]   nonconservative tangential port gain
      stage_mix:    [B]   soft blend toward tangent/transition target
      stage_gain:   [B]   transition potential gain
      memory_amp:   [B]   trap-memory bump amplitude
    """
    def __init__(self, d_obs: int = 6, d_goal: int = 8, d_tok: int = 96, n_layers: int = 2):
        super().__init__()
        self.d_tok = int(d_tok)
        self.obs_enc = nn.Sequential(
            nn.Linear(d_obs, 128), nn.ReLU(), nn.Linear(128, d_tok), nn.ReLU()
        )
        self.goal_enc = nn.Sequential(
            nn.Linear(d_goal, 128), nn.ReLU(), nn.Linear(128, d_tok), nn.ReLU()
        )
        layer = nn.TransformerEncoderLayer(
            d_model=d_tok, nhead=4, dim_feedforward=192, batch_first=True
        )
        self.fuser = nn.TransformerEncoder(layer, num_layers=n_layers)
        self.alpha_head = nn.Sequential(nn.Linear(d_tok, 64), nn.ReLU(), nn.Linear(64, 1))
        self.beta_goal_head = PositiveHead(d_tok, scale=1.25)
        self.beta_icp_head = PositiveHead(d_tok, scale=1.25)
        self.gamma_head = PositiveHead(d_tok, scale=0.75)
        self.tangent_head = PositiveHead(d_tok, scale=1.00)
        self.stage_gain_head = PositiveHead(d_tok, scale=0.75)
        self.memory_amp_head = PositiveHead(d_tok, scale=0.50)
        self.stage_mix_head = nn.Sequential(nn.Linear(d_tok, 96), nn.ReLU(), nn.Linear(96, 1))
        self.value_head = nn.Sequential(nn.Linear(d_tok, 96), nn.ReLU(), nn.Linear(96, 1))

    def encode(self, obs_feats: torch.Tensor, obs_mask: torch.Tensor, goal_feats: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        B, N = obs_feats.shape[:2]
        z_goal = self.goal_enc(goal_feats).unsqueeze(1)
        if N == 0:
            z_obs = obs_feats.new_zeros(B, 0, self.d_tok)
            tokens = z_goal
            pad = torch.zeros(B, 1, dtype=torch.bool, device=goal_feats.device)
        else:
            z_obs = self.obs_enc(obs_feats.reshape(B * N, -1)).reshape(B, N, -1)
            tokens = torch.cat([z_goal, z_obs], dim=1)
            pad = torch.cat([torch.zeros(B, 1, dtype=torch.bool, device=obs_mask.device), ~obs_mask], dim=1)
        z = self.fuser(tokens, src_key_padding_mask=pad)
        return z[:, 0], z_obs

    def forward(self, obs_feats: torch.Tensor, obs_mask: torch.Tensor, goal_feats: torch.Tensor) -> Dict[str, torch.Tensor]:
        ctx, z_obs = self.encode(obs_feats, obs_mask, goal_feats)
        if z_obs.shape[1] == 0:
            alphas = obs_mask.new_zeros(obs_mask.shape, dtype=goal_feats.dtype)
        else:
            alphas = F.softplus(self.alpha_head(z_obs).squeeze(-1))
            alphas = torch.where(obs_mask, alphas, torch.zeros_like(alphas))
        return {
            "alphas": alphas,
            "beta_goal": self.beta_goal_head(ctx),
            "beta_icp": self.beta_icp_head(ctx),
            "gamma": self.gamma_head(ctx),
            "tangent_gain": self.tangent_head(ctx),
            "stage_mix": torch.sigmoid(self.stage_mix_head(ctx)).squeeze(-1),
            "stage_gain": self.stage_gain_head(ctx),
            "memory_amp": self.memory_amp_head(ctx),
            "value": self.value_head(ctx).squeeze(-1),
        }


# -----------------------------------------------------------------------------
# Hamiltonian / pH surrogate
# -----------------------------------------------------------------------------

def icp_barrier(d: torch.Tensor, d_hat: float = 0.90, eps: float = 1e-6, max_b: float = 50.0) -> torch.Tensor:
    """Smooth clipped IPC-like barrier basis B(d), active for 0 < d < d_hat.

    d is clearance after subtracting pseudo-obstacle radius and robot radius.
    The basis is fixed; the network only predicts its coefficients.
    """
    dh = d.new_tensor(float(d_hat))
    safe = torch.clamp(d, min=eps)
    b_in = -(d - dh) ** 2 * torch.log(safe / dh)
    b = torch.where(d < dh, b_in, torch.zeros_like(d))
    # A finite inside-obstacle continuation: strong but not numerically fatal.
    b = torch.where(d <= eps, dh * dh * (-torch.log(dh.new_tensor(eps) / dh)) + (eps - d) ** 2, b)
    return torch.clamp(b, 0.0, max_b)


def local_teacher_pose_sequence(pose0: torch.Tensor, pose_seq: torch.Tensor) -> torch.Tensor:
    """Map world teacher poses [B,H,3] into the initial robot frame."""
    x0, y0, th0 = pose0[:, 0], pose0[:, 1], pose0[:, 2]
    dx = pose_seq[..., 0] - x0[:, None]
    dy = pose_seq[..., 1] - y0[:, None]
    c = torch.cos(th0)[:, None]
    s = torch.sin(th0)[:, None]
    # R^T [dx,dy]
    lx = c * dx + s * dy
    ly = -s * dx + c * dy
    lth = torch.atan2(torch.sin(pose_seq[..., 2] - th0[:, None]), torch.cos(pose_seq[..., 2] - th0[:, None]))
    return torch.stack([lx, ly, lth], dim=-1)


def effective_stage_target(goal: torch.Tensor, obs_feats: torch.Tensor, obs_mask: torch.Tensor, coef: Dict[str, torch.Tensor]) -> torch.Tensor:
    """Blend the goal with a tangential escape target for stage/overlap transit.

    This is a local surrogate for in-between-stage reshaping. If an obstacle is
    frontal/near, the target is nudged along the boundary tangent that points
    most consistently toward the goal. stage_mix controls the blend.
    """
    B, N = obs_feats.shape[:2]
    if N == 0:
        return goal
    c = obs_feats[..., :2]
    rnorm = torch.linalg.norm(c, dim=-1).clamp_min(1e-6)
    front_gate = ((c[..., 0] > -0.20) & (torch.abs(c[..., 1]) < 1.25) & obs_mask).float()
    prox = obs_feats[..., 5] * front_gate
    nearest = prox.argmax(dim=1)
    idx = nearest[:, None, None].expand(-1, 1, 2)
    c_sel = torch.gather(c, 1, idx).squeeze(1)
    n = c_sel / torch.linalg.norm(c_sel, dim=-1, keepdim=True).clamp_min(1e-6)
    t = torch.stack([-n[:, 1], n[:, 0]], dim=-1)
    sign = torch.sign((t * goal).sum(dim=-1, keepdim=True) + 1e-6)
    escape = goal + sign * t * (0.75 + 0.50 * coef["stage_mix"].unsqueeze(-1))
    rho = coef["stage_mix"].unsqueeze(-1)
    return (1.0 - rho) * goal + rho * escape


def shaped_potential(q: torch.Tensor, p: torch.Tensor, obs_feats: torch.Tensor, obs_mask: torch.Tensor,
                     goal_feats: torch.Tensor, coef: Dict[str, torch.Tensor], robot_radius: float) -> torch.Tensor:
    goal = goal_feats[:, :2]
    stage_goal = effective_stage_target(goal, obs_feats, obs_mask, coef)
    V_goal = 0.5 * coef["beta_goal"] * ((q - goal) ** 2).sum(dim=-1)
    V_stage = 0.5 * coef["stage_gain"] * ((q - stage_goal) ** 2).sum(dim=-1)

    if obs_feats.shape[1] > 0:
        C = obs_feats[..., :2]
        R = obs_feats[..., 2]
        d = torch.linalg.norm(q[:, None, :] - C, dim=-1) - R - float(robot_radius)
        B_icp = icp_barrier(d)
        V_icp = (coef["beta_icp"].unsqueeze(-1) * coef["alphas"] * B_icp * obs_mask.float()).sum(dim=-1)
    else:
        V_icp = torch.zeros_like(V_goal)

    # Trap-memory bump: activated by stall feature; its gradient is intentionally
    # slightly shifted behind the vehicle so it pushes out of quasi-static traps.
    stall = goal_feats[:, 7].clamp(0.0, 1.0)
    mem_center = torch.stack([-0.20 * torch.ones_like(stall), torch.zeros_like(stall)], dim=-1)
    sigma2 = 0.35 ** 2
    V_mem = stall * coef["memory_amp"] * torch.exp(-((q - mem_center) ** 2).sum(dim=-1) / (2.0 * sigma2))
    return V_goal + V_stage + V_icp + V_mem


def tangential_port(q: torch.Tensor, obs_feats: torch.Tensor, obs_mask: torch.Tensor,
                    goal_feats: torch.Tensor, coef: Dict[str, torch.Tensor]) -> torch.Tensor:
    if obs_feats.shape[1] == 0:
        return torch.zeros_like(q)
    C = obs_feats[..., :2]
    R = obs_feats[..., 2]
    rel = q[:, None, :] - C
    norm = torch.linalg.norm(rel, dim=-1).clamp_min(1e-6)
    n = rel / norm.unsqueeze(-1)
    t = torch.stack([-n[..., 1], n[..., 0]], dim=-1)
    goal_dir = goal_feats[:, None, :2] - q[:, None, :]
    sign = torch.sign((t * goal_dir).sum(dim=-1, keepdim=True) + 1e-6)
    clear = norm - R
    gate = torch.relu(1.25 - clear) / 1.25
    front = ((C[..., 0] > -0.25) & (torch.abs(C[..., 1]) < 1.50) & obs_mask).float()
    w = gate * front * coef["alphas"]
    port = (w.unsqueeze(-1) * sign * t).sum(dim=1)
    return coef["tangent_gain"].unsqueeze(-1) * port


def integrate_ph(obs_feats: torch.Tensor, obs_mask: torch.Tensor, goal_feats: torch.Tensor,
                 coef: Dict[str, torch.Tensor], horizon: int, dt: float, robot_radius: float,
                 return_energy: bool = False) -> Dict[str, torch.Tensor]:
    B = goal_feats.shape[0]
    q = torch.zeros(B, 2, device=goal_feats.device, dtype=goal_feats.dtype)
    # initial virtual momentum uses measured speed along local x-axis.
    p = torch.stack([goal_feats[:, 4], torch.zeros_like(goal_feats[:, 4])], dim=-1)
    qs, ps, Hs = [], [], []
    for _ in range(int(horizon)):
        q = q.requires_grad_(True)
        V = shaped_potential(q, p, obs_feats, obs_mask, goal_feats, coef, robot_radius)
        grad_q = torch.autograd.grad(V.sum(), q, create_graph=True, retain_graph=True)[0]
        port = tangential_port(q, obs_feats, obs_mask, goal_feats, coef)
        p = p + dt * (-grad_q - coef["gamma"].unsqueeze(-1) * p + port)
        # clamp virtual velocity to avoid exploding surrogate rollouts.
        p_norm = torch.linalg.norm(p, dim=-1, keepdim=True).clamp_min(1e-6)
        p = p * torch.clamp(1.2 / p_norm, max=1.0)
        q = q + dt * p
        qs.append(q)
        ps.append(p)
        if return_energy:
            K = 0.5 * (p * p).sum(dim=-1)
            Hs.append(K + shaped_potential(q, p, obs_feats, obs_mask, goal_feats, coef, robot_radius))
    out = {"q_seq": torch.stack(qs, dim=1), "p_seq": torch.stack(ps, dim=1)}
    if return_energy:
        out["H_seq"] = torch.stack(Hs, dim=1)
    return out


def command_from_ph(obs_feats: torch.Tensor, obs_mask: torch.Tensor, goal_feats: torch.Tensor,
                    coef: Dict[str, torch.Tensor], ack_cfg: AckermannCfg, robot_radius: float) -> torch.Tensor:
    """Convert the current pH vector field at q=0 into an Ackermann twist."""
    B = goal_feats.shape[0]
    q = torch.zeros(B, 2, device=goal_feats.device, dtype=goal_feats.dtype, requires_grad=True)
    p = torch.stack([goal_feats[:, 4], torch.zeros_like(goal_feats[:, 4])], dim=-1)
    V = shaped_potential(q, p, obs_feats, obs_mask, goal_feats, coef, robot_radius)
    grad_q = torch.autograd.grad(V.sum(), q, create_graph=True, retain_graph=True)[0]
    port = tangential_port(q, obs_feats, obs_mask, goal_feats, coef)
    a = -grad_q - coef["gamma"].unsqueeze(-1) * p + port
    desired = p + ack_cfg.dt * a
    desired_angle = torch.atan2(desired[:, 1], desired[:, 0])
    speed = torch.linalg.norm(desired, dim=-1)
    # signed reverse when stall is high and frontal clearance is low: this is a
    # pH memory/port-induced sign, not a direct action head.
    stall = goal_feats[:, 7]
    front_clear = goal_feats[:, 6]
    reverse_gate = ((stall > 0.55) & (front_clear < 0.65)).to(speed.dtype)
    speed_signed = (1.0 - reverse_gate) * speed - reverse_gate * torch.clamp(speed, 0.08, ack_cfg.v_reverse_max)
    omega = 1.8 * torch.atan2(torch.sin(desired_angle), torch.cos(desired_angle))
    raw = torch.stack([speed_signed, omega], dim=-1)
    v, om, _ = project_twist_torch(raw, ack_cfg)
    return torch.stack([v, om], dim=-1)


# -----------------------------------------------------------------------------
# Training
# -----------------------------------------------------------------------------

@dataclass
class TrainPHCfg:
    epochs: int = 20
    samples: int = 40000
    val_samples: int = 4096
    bs: int = 256
    lr: float = 3e-4
    workers: int = 0
    horizon: int = 12
    w_roll: float = 1.0
    w_final: float = 0.5
    w_cmd: float = 0.25
    w_pass: float = 0.05
    w_clear: float = 0.10
    w_beta: float = 0.05
    w_coef: float = 1e-4
    seed: int = 2026
    device: str = "cuda" if torch.cuda.is_available() else "cpu"


def build_stage1_cfg(args: argparse.Namespace) -> Stage1Cfg:
    return Stage1Cfg(
        scene=SceneCfg(
            robot_radius=args.robot_radius,
            n_obs_range=(args.n_obs_min, args.n_obs_max),
            corridor_half_width=args.corridor_half_width,
        ),
        scan=LaserScanCfg(
            n_beams=args.n_beams,
            fov=args.fov_deg * math.pi / 180.0,
            range_max=args.range_max,
            noise_std=args.scan_noise,
            dropout_prob=args.scan_dropout,
        ),
        adapter=AdapterCfg(max_tokens=args.max_tokens),
        ackermann=AckermannCfg(
            wheelbase=args.wheelbase,
            v_max=args.v_max,
            v_reverse_max=args.v_reverse_max,
            max_steering_angle=args.max_steering_angle,
            min_turning_radius=args.min_turning_radius,
            dt=args.dt,
        ),
        recovery=RecoveryCfg(
            p_recovery_sample=args.p_recovery,
            move_speed_floor=args.move_speed_floor,
            stall_steps_trigger=args.stall_steps_trigger,
            train_horizon=args.horizon,
        ),
        seed=args.seed,
    )


def clearance_penalty(q_seq: torch.Tensor, obs_feats: torch.Tensor, obs_mask: torch.Tensor, robot_radius: float) -> torch.Tensor:
    if obs_feats.shape[1] == 0:
        return q_seq.new_zeros(())
    C = obs_feats[:, None, :, :2]
    R = obs_feats[:, None, :, 2]
    q = q_seq[:, :, None, :]
    clear = torch.linalg.norm(q - C, dim=-1) - R - float(robot_radius)
    clear = torch.where(obs_mask[:, None, :], clear, torch.full_like(clear, 1e3))
    min_clear = clear.min(dim=-1).values
    return (torch.relu(0.05 - min_clear) ** 2).mean()


def run_epoch(model: StagePHCoefNet, loader: DataLoader, train_cfg: TrainPHCfg, sim_cfg: Stage1Cfg,
              optimizer: torch.optim.Optimizer | None = None) -> Dict[str, float]:
    is_train = optimizer is not None
    model.train(is_train)
    logs = {"loss": 0.0, "roll": 0.0, "final": 0.0, "cmd": 0.0, "pass": 0.0, "clear": 0.0,
            "beta": 0.0, "coef": 0.0, "cmd_mae_v": 0.0, "cmd_mae_om": 0.0,
            "mean_alpha": 0.0, "mean_gamma": 0.0, "mean_stage_mix": 0.0}
    n = 0
    for batch in loader:
        obs = batch["obs_feats"].to(train_cfg.device)
        mask = batch["obs_mask"].to(train_cfg.device)
        goal = batch["goal_feats"].to(train_cfg.device)
        pose = batch["pose"].to(train_cfg.device)
        pose_seq = batch["pose_seq"].to(train_cfg.device)
        cmd_tgt = batch["cmd"].to(train_cfg.device)
        beta_tgt = batch["beta_seq"].to(train_cfg.device)

        coef = model(obs, mask, goal)
        out = integrate_ph(obs, mask, goal, coef, train_cfg.horizon, sim_cfg.ackermann.dt,
                           sim_cfg.scene.robot_radius, return_energy=True)
        target_local = local_teacher_pose_sequence(pose, pose_seq)
        q_seq = out["q_seq"]
        H_seq = out["H_seq"]
        raw_cmd = command_from_ph(obs, mask, goal, coef, sim_cfg.ackermann, sim_cfg.scene.robot_radius)

        L_roll = F.mse_loss(q_seq, target_local[..., :2])
        L_final = F.mse_loss(q_seq[:, -1, :], target_local[:, -1, :2])
        L_cmd = F.mse_loss(raw_cmd, cmd_tgt)
        dH = H_seq[:, 1:] - H_seq[:, :-1]
        L_pass = torch.relu(dH + 0.01 * (out["p_seq"][:, :-1, :] ** 2).sum(dim=-1)).mean() if H_seq.shape[1] > 1 else H_seq.new_zeros(())
        L_clear = clearance_penalty(q_seq, obs, mask, sim_cfg.scene.robot_radius)
        # beta teacher supervises soft ICP gain level rather than direct actions.
        beta_mean_tgt = beta_tgt.mean(dim=1)
        beta_pred = torch.clamp(coef["beta_icp"], 0.0, 4.0) / 4.0
        L_beta = F.mse_loss(beta_pred, beta_mean_tgt)
        L_coef = (coef["alphas"].mean() + coef["beta_goal"].mean() + coef["beta_icp"].mean() + coef["tangent_gain"].mean())
        L = (train_cfg.w_roll * L_roll + train_cfg.w_final * L_final + train_cfg.w_cmd * L_cmd
             + train_cfg.w_pass * L_pass + train_cfg.w_clear * L_clear + train_cfg.w_beta * L_beta
             + train_cfg.w_coef * L_coef)

        if is_train:
            optimizer.zero_grad(set_to_none=True)
            L.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            optimizer.step()

        with torch.no_grad():
            err = torch.abs(raw_cmd - cmd_tgt)
            logs["loss"] += float(L.item())
            logs["roll"] += float(L_roll.item())
            logs["final"] += float(L_final.item())
            logs["cmd"] += float(L_cmd.item())
            logs["pass"] += float(L_pass.item())
            logs["clear"] += float(L_clear.item())
            logs["beta"] += float(L_beta.item())
            logs["coef"] += float(L_coef.item())
            logs["cmd_mae_v"] += float(err[:, 0].mean().item())
            logs["cmd_mae_om"] += float(err[:, 1].mean().item())
            logs["mean_alpha"] += float(coef["alphas"].mean().item()) if coef["alphas"].numel() else 0.0
            logs["mean_gamma"] += float(coef["gamma"].mean().item())
            logs["mean_stage_mix"] += float(coef["stage_mix"].mean().item())
        n += 1
    for k in logs:
        logs[k] /= max(1, n)
    return logs


def main():
    ap = argparse.ArgumentParser("Train Stage-1 pH Hamiltonian/ICP coefficient model")
    ap.add_argument("--epochs", type=int, default=20)
    ap.add_argument("--samples", type=int, default=40000)
    ap.add_argument("--val-samples", type=int, default=4096)
    ap.add_argument("--bs", type=int, default=256)
    ap.add_argument("--lr", type=float, default=3e-4)
    ap.add_argument("--workers", type=int, default=0)
    ap.add_argument("--threads", type=int, default=1)
    ap.add_argument("--outdir", type=str, default="checkpoints/stage1_ph_energy")
    ap.add_argument("--resume", type=str, default=None,
                    help="Optional checkpoint to initialize the pH coefficient model from. Used for staged fine-tuning.")
    ap.add_argument("--resume-optimizer", action="store_true",
                    help="Also restore optimizer state from --resume. Default is model-only fine-tuning with a fresh optimizer.")
    ap.add_argument("--continue-epoch-numbering", action="store_true",
                    help="Continue epoch numbering from the resumed checkpoint. Default restarts local phase epoch count at 0.")
    ap.add_argument("--seed", type=int, default=2026)
    ap.add_argument("--horizon", type=int, default=12)

    ap.add_argument("--wheelbase", type=float, default=0.324)
    ap.add_argument("--v-max", type=float, default=0.80)
    ap.add_argument("--v-reverse-max", type=float, default=0.25)
    ap.add_argument("--max-steering-angle", type=float, default=0.396)
    ap.add_argument("--min-turning-radius", type=float, default=0.80)
    ap.add_argument("--dt", type=float, default=0.10)
    ap.add_argument("--robot-radius", type=float, default=0.23)

    ap.add_argument("--n-beams", type=int, default=181)
    ap.add_argument("--fov-deg", type=float, default=270.0)
    ap.add_argument("--range-max", type=float, default=6.0)
    ap.add_argument("--scan-noise", type=float, default=0.015)
    ap.add_argument("--scan-dropout", type=float, default=0.01)
    ap.add_argument("--max-tokens", type=int, default=24)
    ap.add_argument("--n-obs-min", type=int, default=8)
    ap.add_argument("--n-obs-max", type=int, default=20)
    ap.add_argument("--corridor-half-width", type=float, default=0.70)
    ap.add_argument("--p-recovery", type=float, default=0.30)
    ap.add_argument("--move-speed-floor", type=float, default=0.10)
    ap.add_argument("--stall-steps-trigger", type=int, default=8)

    ap.add_argument("--w-roll", type=float, default=1.0)
    ap.add_argument("--w-final", type=float, default=0.5)
    ap.add_argument("--w-cmd", type=float, default=0.25)
    ap.add_argument("--w-pass", type=float, default=0.05)
    ap.add_argument("--w-clear", type=float, default=0.10)
    ap.add_argument("--w-beta", type=float, default=0.05)
    ap.add_argument("--w-coef", type=float, default=1e-4)
    args = ap.parse_args()

    torch.set_num_threads(max(1, int(args.threads)))
    torch.manual_seed(args.seed)
    os.makedirs(args.outdir, exist_ok=True)

    sim_cfg = build_stage1_cfg(args)
    train_cfg = TrainPHCfg(
        epochs=args.epochs, samples=args.samples, val_samples=args.val_samples, bs=args.bs,
        lr=args.lr, workers=args.workers, horizon=args.horizon,
        w_roll=args.w_roll, w_final=args.w_final, w_cmd=args.w_cmd, w_pass=args.w_pass,
        w_clear=args.w_clear, w_beta=args.w_beta, w_coef=args.w_coef, seed=args.seed,
    )
    train_ds = Stage1AckermannDataset(n_samples=args.samples, cfg=sim_cfg, seed=args.seed)
    val_ds = Stage1AckermannDataset(n_samples=args.val_samples, cfg=sim_cfg, seed=args.seed + 100000)
    train_dl = DataLoader(train_ds, batch_size=args.bs, shuffle=True, num_workers=args.workers,
                          collate_fn=collate_stage1, drop_last=False)
    val_dl = DataLoader(val_ds, batch_size=args.bs, shuffle=False, num_workers=args.workers,
                        collate_fn=collate_stage1, drop_last=False)

    model = StagePHCoefNet()
    model.to(train_cfg.device)
    opt = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=1e-4)
    model_cfg = {"d_tok": model.d_tok, "kind": "StagePHCoefNet"}

    resume_meta: Dict[str, Any] = {}
    start_epoch = 0
    if args.resume is not None:
        resume_ckpt = torch.load(args.resume, map_location=train_cfg.device)
        model.load_state_dict(resume_ckpt["model_state_dict"], strict=True)
        resume_meta = {
            "path": args.resume,
            "source_epoch": int(resume_ckpt.get("epoch", -1)),
            "source_val_logs": resume_ckpt.get("val_logs", {}),
            "source_train_cfg": resume_ckpt.get("train_cfg", {}),
        }
        if args.resume_optimizer:
            if "optimizer_state_dict" not in resume_ckpt:
                raise ValueError(f"--resume-optimizer requested, but {args.resume} has no optimizer_state_dict")
            opt.load_state_dict(resume_ckpt["optimizer_state_dict"])
        if args.continue_epoch_numbering:
            start_epoch = int(resume_ckpt.get("epoch", -1)) + 1
        print({
            "resumed_from": args.resume,
            "source_epoch": resume_meta["source_epoch"],
            "resume_optimizer": bool(args.resume_optimizer),
            "start_epoch": int(start_epoch),
        })
    with open(os.path.join(args.outdir, "stage1_ph_config.json"), "w") as f:
        json.dump({
            "sim_cfg": stage1_cfg_to_dict(sim_cfg),
            "train_cfg": asdict(train_cfg),
            "model_cfg": model_cfg,
            "resume": resume_meta,
        }, f, indent=2)

    best = float("inf")
    for local_ep in range(args.epochs):
        ep = start_epoch + local_ep
        tr = run_epoch(model, train_dl, train_cfg, sim_cfg, opt)
        # Validation still needs autograd for differentiating the shaped potential.
        va = run_epoch(model, val_dl, train_cfg, sim_cfg, None)
        print({f"ep{ep}/train_{k}": round(v, 6) for k, v in tr.items()} |
              {f"ep{ep}/val_{k}": round(v, 6) for k, v in va.items()})
        ckpt = {
            "epoch": ep,
            "local_epoch": local_ep,
            "model_state_dict": model.state_dict(),
            "optimizer_state_dict": opt.state_dict(),
            "sim_cfg": stage1_cfg_to_dict(sim_cfg),
            "train_cfg": asdict(train_cfg),
            "model_cfg": model_cfg,
            "resume": resume_meta,
            "train_logs": tr,
            "val_logs": va,
        }
        torch.save(ckpt, os.path.join(args.outdir, "latest.pt"))
        if va["loss"] < best:
            best = va["loss"]
            torch.save(ckpt, os.path.join(args.outdir, "best.pt"))
        if ep % 5 == 0 or ep == args.epochs - 1:
            torch.save(ckpt, os.path.join(args.outdir, f"epoch_{ep:03d}.pt"))


if __name__ == "__main__":
    main()
